type User {
    username: String @unique
    email: String! @unique
    governingAgency: String
    savedCourses: [SavedCourses!] @relation
    name: String
    title: String
    company: String
    website: String
    bio: String
    linkedin: String
    zillow: String
    twitter: String
    instagram: String
    facebook: String
    theme: String
    personalEmail: String
    phone: String
    officePhone: String
    addressLine1: String
    addressLine2: String
    city: String
    state: String
    zip: String
    licenseType: String
    licenseNumber: String
    licensurePeriod: [LicensurePeriod] @relation
    alerts: Boolean
    news: Boolean
    hideContactInfo: Boolean
    profileImage: String
    isRealtor: Boolean
}

type Course {
    name: String!
    provider: String!
    date: String!
    hours: Int
    governingAgency: String!
    saved: String!
}

type SavedCourses {
    name: String!
    provider: String!
    date: String!
    hours: Int
    governingAgency: String!
    saved: String!
    owner: String!
    username: String!
}

type Credit {
    name: String!
    user: User! @relation
    provider: String!
    date: String!
    hours: Int!
    governingAgency: String
    description: String
    credits: String!
}

type Query {
    allCourses: [Course!]
    allUserCourses: [Course!]
}

type LicensurePeriod{
    startDate: String!
    endDate: String!
    creditsEarned: Int!
    creditsRequired: Int!
    credits: [Credit!] @relation
}
