type User {
    username: String @unique
    email: String! @unique
    governingAgency: String
    savedCourses: [SavedCourses] @relation
    name: String
    title: String
    company: String
    website: String
    bio: String
    linkedin: String
    zillow: String
    twitter: String
    instagram: String
    facebook: String
    theme: String
    personalEmail: String
    phone: String
    officePhone: String
    addressLine1: String
    addressLine2: String
    city: String
    state: String
    zip: String
    licenseType: String
    licenseNumber: String
    licensurePeriods: [LicensurePeriod] @relation
    alerts: Boolean
    news: Boolean
    hideContactInfo: Boolean
    profileImage: String
    isRealtor: Boolean
}

type Course {
    name: String!
    provider: String!
    date: String!
    hours: Int!
    governingAgency: String!
    saved: Boolean
    description: String
    required: Boolean
    contactName: String
    contactPhone: String
}
# Annual Commission Update Course

type SavedCourses {
    name: String!
    provider: String!
    date: String!
    hours: Int
    governingAgency: String!
    saved: Boolean
    owner: String!
    username: String!
    description: String
    user: User! @relation
    contactName: String
    contactPhone: String
}

type Credit {
    name: String!
    user: User! @relation
    provider: String!
    date: String!
    hours: Int!
    governingAgency: String
    description: String
    certificateImage: String!
    licensurePeriod: LicensurePeriod! @relation
}

type Query {
    allCourses: [Course!]
    allUserCourses: [Course!]
}

type LicensurePeriod {
    startDate: String!
    endDate: String!
    creditsEarned: Int!
    creditsRequired: Int!
    credits: [Credit!] @relation
    user: User! @relation
}


#---- GET_COURSES,
#---- GET_COURSES_BY_PROVIDER,
#---- CREATE_COURSE

# GET_SAVEDCOURSES_BY_USER,
# CREATE_SAVEDCOURSE,
# DELETE_SAVEDCOURSE,

# CREATE_PROVIDER,
# GET_PROVIDERS,

# GET_USER,
# UPDATE_USER,
# CREATE_USER,

# GET_LICENSUREPERIODS_BY_USER,
# CREATE_LICENSUREPERIORD_FOR_USER,
# UPDATE_LICENSUREPERIORD_FOR_USER,
# DELETE_LICENSUREPERIORD_FOR_USER,

# GET_CREDIT_BY_ID,
# CREATE_CREDIT,
# UPDATE_CREDIT,
# DELETE_CREDIT,
# GET_USER_CREDITS,